### ISSUE TITLE
Сместить кнопку UNMUTE вниз

### ISSUE THREAD

**Issue by anton-kuptsov** [Schizoproletariat/papasrapa.com#5]
![photo_2021-09-09_16-16-02](https://user-images.githubusercontent.com/39290991/132800360-26b20691-be10-4413-9d72-940cfde2afef.jpg)

**Comment by anton-kuptsov** [comment]
@nkabardin сместил вниз, на рсстояние 10% от нижнего края, т.к. там расположены стандратные контролы. добавил детект тачскрина. при тачскрине убирается кнопка UNMUTE, т.к. появляется стандартная кнопка  проигрывателя TAP TO UNMUTE

**Comment by nkabardin** [comment]
круто! отличная идея, я об этом подумал впервые вчера а ты сделал уже
